config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  post 'new_follow', to: 'artists#new_follow'
  get 'dashboard', to: 'dashboards#show'
  post 'spotify_to_dashboard', to: 'dashboards#spotify_to_dashboard'
  get 'feed', to: 'feeds#show'
  get '/auth/spotify/callback', to: 'users#spotify'
  post 'add_from_spotify', to: 'artists#add_from_spotify'
  post 'add_dismissed_to_user', to: 'users#dismissed'
  resources :artists, only: [ :index, :create ] do
    member do
      post 'toggle_follow', to: 'artists#toggle_follow'
    end
  end
  get '/user' => "welcome#index", :as => :user_root
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Postmark throwing errors -- commenting this out until Postmark account is verified
  # after_create :send_welcome_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_favoritor

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    # Now you can access user's private data, create playlists and much more

    # Set user's attributes based off spotify sign in
    current_user.spotify_id = spotify_user.id
    current_user.country = spotify_user.country
    unless spotify_user.images.first == nil
      image_url = spotify_user.images.first.url
      image_url.gsub!('https://','http://')
      current_user.image_url = image_url
    end
    current_user.save!

    # Get user's favorite artists from spotify
    @spotify_favorites = []
    @spotify_ids = []
    following_on_spotify = spotify_user.following(type: "artist", limit: 25)
    following_on_spotify.each do |artist|
      @spotify_ids << artist.id
      @spotify_favorites << Artist.new(name: artist.name, spotify_id: artist.id, image_url: artist.images.first ? artist.images.first["url"] : "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80")
    end
    favorites_from_spotify = spotify_user.top_artists(limit: 25)
    favorites_from_spotify.each do |artist|
      @spotify_ids << artist.id
      @spotify_favorites << Artist.new(name: artist.name, spotify_id: artist.id, image_url: artist.images.first ? artist.images.first["url"] : "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80")
    end
    @spotify_ids.uniq!
    @spotify_favorites.uniq! { |artist| artist.spotify_id }
  end

  def dismissed
    current_user.dismissed = true
    current_user.save!
    redirect_to artists_path
  end
end

app/views/users/spotify.html.erb
<div class="container">
  <div class="title-container" data-controller="loading">
      <div>
        <h3>Your Spotify Favorites</h3>
        <h4>Choose who to follow</h4>
      </div>
      <div class="spotify-buttons">
        <%= link_to "Follow all", add_from_spotify_path( favorites: @spotify_ids ), method: :post, class: "btn btn-outline", data: { action: "click->loading#followSpinner", loading_target: 'follow' } %>
        <%= link_to "Done", spotify_to_dashboard_path, method: :post, class: "btn btn-filled", data: { action: "click->loading#doneSpinner", loading_target: 'done' } %>
      </div>
  </div>

  <div class="artist-cards row">
    <% @spotify_favorites.each do |artist| %>
      <div class="col-md-4">
        <% if Artist.find_by_name(artist.name) == nil %>
            <%= render "components/spotify_artist_card", artist: artist, user: current_user %>
        <% else %>
          <% db_artist = Artist.find_by_name(artist.name) %>
          <%= render 'components/artist_card', artist: db_artist, user: current_user %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>