config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  post 'new_follow', to: 'artists#new_follow'
  get 'dashboard', to: 'dashboards#show'
  post 'spotify_to_dashboard', to: 'dashboards#spotify_to_dashboard'
  get 'feed', to: 'feeds#show'
  get '/auth/spotify/callback', to: 'users#spotify'
  post 'add_from_spotify', to: 'artists#add_from_spotify'
  post 'add_dismissed_to_user', to: 'users#dismissed'
  resources :artists, only: [ :index, :create ] do
    member do
      post 'toggle_follow', to: 'artists#toggle_follow'
    end
  end
  get '/user' => "welcome#index", :as => :user_root
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "releasy_logo.png" %>
  <% end %>

  <% if user_signed_in? %>
    <div class="mr-auto">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= "active" if params[:controller] == "feeds" %>">
          <%= link_to "Feed", feed_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= "active" if params[:controller] == "dashboards" %>">
          <%= link_to "Following", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= "active" if params[:controller] == "artists" %>">
          <%= link_to "Find", artists_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <div class="nav-item dropdown">
        <div class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-image: url('<%= current_user.image_url %>')"></div>
        <%# <%= image_tag current_user.image_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Account", "#", class: "dropdown-item" %>
          <%= link_to "Connect to Spotify", "/auth/spotify", class: "dropdown-item", method: :post %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>
    <% end %>
  </div>
</div>